<Project Sdk="Dalamud.NET.Sdk/15.0.0">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Platforms>x64</Platforms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>false</AllowUnsafeBlocks>
		<UseWindowsForms>true</UseWindowsForms>
		<Version>1.0.4.0</Version>
		<AssemblyVersion>1.0.4.0</AssemblyVersion>
		<FileVersion>1.0.4.0</FileVersion>
		<AssemblyName>SyncThief</AssemblyName>
		<RootNamespace>SyncThief</RootNamespace>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Penumbra.Api" Version="5.19.2" />
	</ItemGroup>

	<ItemGroup>
		<None Update="SyncThief.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
